services:
  - type: web
    name: placement-backend
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8080
      - key: MONGO_URI
        sync: false

staticSites:
  - name: placement-frontend
    rootDir: Frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: placement-backend
          property: url
